-- Update exercises with English names (Comprehensive List)
UPDATE exercises SET name_en = 'Triceps Extension' WHERE name = '트라이셉스 익스텐션';
UPDATE exercises SET name_en = 'Dumbbell Shoulder Press' WHERE name = '덤벨 숄더 프레스';
UPDATE exercises SET name_en = 'Treadmill' WHERE name = '러닝머신';
UPDATE exercises SET name_en = 'Plank' WHERE name = '플랭크';
UPDATE exercises SET name_en = 'Seated Row' WHERE name = '시티드 로우';
UPDATE exercises SET name_en = 'Leg Raises' WHERE name = '레그 레이즈';
UPDATE exercises SET name_en = 'Back Extension' WHERE name = '백 익스텐션';
UPDATE exercises SET name_en = 'Dips' WHERE name = '딥스';
UPDATE exercises SET name_en = 'Push Up' WHERE name = '푸쉬업';
UPDATE exercises SET name_en = 'Pec Deck Fly' WHERE name = '펙덱 플라이';
UPDATE exercises SET name_en = 'Lat Pulldown' WHERE name = '랫 풀 다운';
UPDATE exercises SET name_en = 'Chest Press Machine' WHERE name = '체스트 프레스 머신';
UPDATE exercises SET name_en = 'Stair Climber' WHERE name = '천국의 계단';
UPDATE exercises SET name_en = 'Lunge' WHERE name = '런지';
UPDATE exercises SET name_en = 'Barbell Row' WHERE name = '바벨 로우';
UPDATE exercises SET name_en = 'Crunch' WHERE name = '크런치';
UPDATE exercises SET name_en = 'Hanging Leg Raise' WHERE name = '행잉 레그 레이즈';
UPDATE exercises SET name_en = 'Cable Pushdown' WHERE name = '케이블 푸쉬 다운';
UPDATE exercises SET name_en = 'One Arm Dumbbell Row' WHERE name = '원암 덤벨 로우';
UPDATE exercises SET name_en = 'Incline Bench Press' WHERE name = '인클라인 벤치프레스';
UPDATE exercises SET name_en = 'Hack Squat' WHERE name = '핵 스쿼트';
UPDATE exercises SET name_en = 'Side Lateral Raise' WHERE name = '사이드 레터럴 레이즈';
UPDATE exercises SET name_en = 'Front Raise' WHERE name = '프론트 레이즈';
UPDATE exercises SET name_en = 'Pull Up' WHERE name = '풀업 (턱걸이)';
UPDATE exercises SET name_en = 'Deadlift' WHERE name = '데드리프트';
UPDATE exercises SET name_en = 'Leg Curl' WHERE name = '레그 컬';
UPDATE exercises SET name_en = 'Leg Extension' WHERE name = '레그 익스텐션';
UPDATE exercises SET name_en = 'Dumbbell Press' WHERE name = '덤벨 프레스';
UPDATE exercises SET name_en = 'Dumbbell Curl' WHERE name = '덤벨 컬';
UPDATE exercises SET name_en = 'Barbell Curl' WHERE name = '바벨 컬';
UPDATE exercises SET name_en = 'Dumbbell Fly' WHERE name = '덤벨 플라이';
UPDATE exercises SET name_en = 'Skull Crusher' WHERE name = '스컬 크러셔';
UPDATE exercises SET name_en = 'Leg Press' WHERE name = '레그 프레스';
UPDATE exercises SET name_en = 'Bench Press' WHERE name = '벤치프레스';
UPDATE exercises SET name_en = 'Calf Raise' WHERE name = '카프 레이즈';
UPDATE exercises SET name_en = 'Hammer Curl' WHERE name = '해머 컬';
UPDATE exercises SET name_en = 'Squat' WHERE name = '스쿼트';
UPDATE exercises SET name_en = 'Face Pull' WHERE name = '페이스 풀';
UPDATE exercises SET name_en = 'Indoor Cycle' WHERE name = '실내 자전거';
UPDATE exercises SET name_en = 'Overhead Press' WHERE name = '오버헤드 프레스';
